M48
; DRILL file {KiCad 8.0.7} date 2024-12-28T18:40:46+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-28T18:40:46+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X100.33Y-62.23
X110.49Y-62.23
X119.38Y-62.23
X129.54Y-62.23
T2
X105.41Y-62.23
X124.46Y-62.23
M30
